export enum BLOG_CATEGORY {
    SLEEP_BLOG = "SLEEP_BLOG",
    FEAR_BLOG = "FEAR_BLOG",
    STRESS_BLOG = "STRESS_BLOG",
    ANXITY_BLOG = "ANXITY_BLOG",
    PRODUCTIVITY_BLOG = "PRODUCTIVITY_BLOG",
};

