export enum MOOD_TYPE {
    HAPPY = "HAPPY",
    STRESSED = "STRESSED",
    ANXITY = "ANXITY",
    SLEEPY = "SLEEPY",
    SAD = "SAD",
    NO_MOTIVATION = "NO_MOTIVATION",
    DEPRESSION = "DEPRESSION",
    PERSONALITY = "PERSONALITY"
}

export enum SOURCE {
    HOME = "HOME",
    SELF_ASSESSMENT = "SELF_ASSESSMENT"
}