export enum FOLDER_NAMES {
  IMAGE = "image",
  SEATING_PLAN = "seatingPlan",
  BUSINESSPROFILEIMAGE = "businessProfileImage",
  GALLERY = "gallery",
  PROFILE_IMAGE = "profileImage",
  CHILD_IMAGE = "childImage",
  IMAGES = "images",
  LICENSE = "license",
  DRIVER_LICENSE = "driverLicense",
  INSURANCE = "insurance",
  PERMITS = "permits",
  BANNER = "banner",
  LOGO = "logo",
  AUDIO = "audio",
  VIDEO = "video",
  DOCUMENT = "document",
  THUMBNAIL = "thumbnail",
  OTHERS = "others",
  REMOVE_IMAGE = "removeImage",
}
